name: CI - Development  # Updated this line from 'code name'

on:
  push:
    branches:
      - develop  # Runs on push to the 'develop' branch
  pull_request:
    branches:
      - develop  # Runs on pull request to the 'develop' branch
    paths:
      - "feature/*"  # Only for PRs related to 'feature/*' paths

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Set execute permissions for eslint
        run: chmod +x ./node_modules/.bin/eslint
      - name: Run Linting
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
